import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseDocument } from "@/main/document/document-worker";
import { DEFAULT_DOCUMENT_LIMITS } from "@/main/document/document-limits";
import {
  createDocxFixture,
  createPdfFixture,
  createPptxFixture,
  createXlsxFixture,
} from "../helpers/document-fixtures";

const representativeFixtures = fileURLToPath(
  new URL("../fixtures/documents/", import.meta.url)
);

describe("document parser adapters", () => {
  it.each([
    ["pdf", "sample.pdf", createPdfFixture(), "PDF fixture text"],
    ["docx", "sample.docx", createDocxFixture(), "DOCX fixture text"],
    ["xlsx", "sample.xlsx", createXlsxFixture(), "Alpha"],
    ["pptx", "sample.pptx", createPptxFixture(), "PPTX fixture text"],
  ] as const)("normalizes %s content", async (format, fileName, data, expected) => {
    const directory = await mkdtemp(path.join(tmpdir(), "zora-document-parser-"));
    const filePath = path.join(directory, fileName);
    await writeFile(filePath, data);
    try {
      const snapshot = await parseDocument({
        id: "test",
        filePath,
        format,
        fingerprint: `${format}-fixture`,
        limits: DEFAULT_DOCUMENT_LIMITS,
      });
      expect(snapshot.format).toBe(format);
      expect(snapshot.blocks.map((block) => block.markdown).join("\n")).toContain(expected);
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  });

  describe("representative files generated by mature document libraries", () => {
    it.each([
      {
        format: "pdf" as const,
        fileName: "northstar-operations.pdf",
        marker: "PDF_REALISTIC_MARKER",
        assertSnapshot: (snapshot: Awaited<ReturnType<typeof parseDocument>>) => {
          expect(snapshot.metadata.pages).toBe(2);
          expect(snapshot.blocks).toHaveLength(2);
          expect(snapshot.blocks[1]).toMatchObject({ kind: "page", page: 2 });
        },
      },
      {
        format: "docx" as const,
        fileName: "northstar-review.docx",
        marker: "DOCX_REALISTIC_MARKER",
        assertSnapshot: (snapshot: Awaited<ReturnType<typeof parseDocument>>) => {
          const markdown = snapshot.blocks.map((block) => block.markdown).join("\n");
          expect(markdown).toContain("# Northstar Product Review");
          expect(markdown).toContain("- Preserve heading and list structure");
          expect(markdown).toContain("| Workstream | Owner | Status |");
          expect(markdown).toContain("1. Validation checklist");
        },
      },
      {
        format: "xlsx" as const,
        fileName: "northstar-dashboard.xlsx",
        marker: "XLSX_REALISTIC_MARKER",
        assertSnapshot: (snapshot: Awaited<ReturnType<typeof parseDocument>>) => {
          const markdown = snapshot.blocks.map((block) => block.markdown).join("\n");
          expect(snapshot.metadata.sheets).toEqual([
            { name: "Summary", rows: 8 },
            { name: "Regional Data", rows: 4 },
            { name: "Internal Notes", rows: 1, hidden: true },
          ]);
          expect(markdown).toContain("A: [合并 A1:D1] Northstar Usage Dashboard");
          expect(markdown).toContain("A: 2026-04-01");
          expect(markdown).toContain("C: =SUM(C3:C5)");
          expect(markdown).toContain("Generated fixture: do not use as business data");
        },
      },
      {
        format: "pptx" as const,
        fileName: "northstar-launch.pptx",
        marker: "PPTX_REALISTIC_MARKER",
        assertSnapshot: (snapshot: Awaited<ReturnType<typeof parseDocument>>) => {
          const markdown = snapshot.blocks.map((block) => block.markdown).join("\n");
          expect(snapshot.metadata.slides).toBe(3);
          expect(markdown).toContain("PPTX_SPEAKER_NOTE_MARKER");
          expect(markdown).toContain("| Capability | Owner | Status |");
          expect(markdown).toContain("[图表]");
        },
      },
    ])("parses $format structure and content", async ({
      format,
      fileName,
      marker,
      assertSnapshot,
    }) => {
      const snapshot = await parseDocument({
        id: `representative-${format}`,
        filePath: path.join(representativeFixtures, fileName),
        format,
        fingerprint: `representative-${format}`,
        limits: DEFAULT_DOCUMENT_LIMITS,
      });
      expect(snapshot.format).toBe(format);
      expect(snapshot.blocks.map((block) => block.markdown).join("\n")).toContain(marker);
      assertSnapshot(snapshot);
    });
  });

  it("enforces PDF and spreadsheet complexity limits", async () => {
    const directory = await mkdtemp(path.join(tmpdir(), "zora-document-limits-"));
    const pdfPath = path.join(directory, "sample.pdf");
    const xlsxPath = path.join(directory, "sample.xlsx");
    await Promise.all([
      writeFile(pdfPath, createPdfFixture()),
      writeFile(xlsxPath, createXlsxFixture()),
    ]);
    try {
      await expect(parseDocument({
        id: "pdf-limit",
        filePath: pdfPath,
        format: "pdf",
        fingerprint: "pdf-limit",
        limits: { ...DEFAULT_DOCUMENT_LIMITS, maxPdfPages: 0 },
      })).rejects.toMatchObject({ officeIssue: { code: "DOCUMENT_TOO_COMPLEX" } });
      await expect(parseDocument({
        id: "xlsx-limit",
        filePath: xlsxPath,
        format: "xlsx",
        fingerprint: "xlsx-limit",
        limits: { ...DEFAULT_DOCUMENT_LIMITS, maxXlsxCells: 1 },
      })).rejects.toBeDefined();
    } finally {
      await rm(directory, { recursive: true, force: true });
    }
  });
});
